name: CoolShitzz
favicon: null
layout_spectrum: 0.75182
typography_spectrum: 0.8772
title: Seeing differently.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#494949'
    - '#dadad9'
    - '#959492'
    - '#bdbdbd'
    - '#a76248'
  brandStrength: 1
  lightness: 0.18317510094493628
  saturation: 1
  rhythmicContrast: 0.41671615396626294
purpose: []
